name = ""
account_id = ""
route = ""
zone_id = ""
workers_dev = true
type = "webpack"
webpack_config = "https://broken-glitter-7dbc.topwisata.workers.dev"

[env.dev]
vars = { MODE = "dev" }

[env.beta]
vars = { MODE = "beta" }

[env.prod]
vars = { MODE = "prod" }

